apiVersion: apps/v1
kind: Deployment
metadata:
#  labels:
#    app: my-app
  name: my-deploy-app
#  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
#      creationTimestamp: null
      labels:
        app: my-app
    spec:
#      serviceAccountName: ksa-name
      containers:
        - name: docker-image
          image: europe-west4-docker.pkg.dev/aerial-vehicle-328606/docker-repo/docker-image:tag1
#          imagePullPolicy: IfNotPresent
#          resources: {}
#          terminationMessagePath: /dev/termination-log
#          terminationMessagePolicy: File
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database
        - name: cloud-sql-proxy
          # It is recommended to use the latest version of the Cloud SQL proxy
          # Make sure to update on a regular schedule!
          image: gcr.io/cloudsql-docker/gce-proxy:1.26.0
          command:
            - "/cloud_sql_proxy"
            - "-instances=aerial-vehicle-328606:europe-west4:my-sql=tcp:3306"
            - "-credential_file=/secrets/service_account.json"
          volumeMounts:
            - name: sa-secret-volume
              mountPath: /secrets/
              readOnly: true
      volumes:
        - name: sa-secret-volume
          secret:
            secretName: service-account-secret